### PR TITLE
monk: init, start, restart, setproperty

### PR DESCRIPTION
**Pull request by ebuchman**
This fixes the no keyRing problem - the module was never being initialized so of course there was no key ring!

Also, fixes an issue with restarting and cleaner handling of config values.

### CODE REVIEW

**Comment by androlo** [comment]
it is, except its done in restart. no point in starting monk up until a dapp is loaded, and that's when init and start is both run.

**Comment by androlo** [comment]
remember it worked for you but not for us

**Comment by androlo** [comment]
why are you poking around in decerver? this doesn't fix anything it just break things even more. this works perfectly fine on master.

**Comment by androlo** [comment]
ok so the truth is i felt ashamed you had to go do my job for me. this iswhat the separation will fix. issues with dependencies i can fix myself by just reverting to latest working. still an issue? my fault. otherwise not. same for you. time will be saved.

**Comment by androlo** [comment]
and effort.

**Comment by ebuchman** [comment]
it didnt actually work for me i must have had my branches wrong.

im poking aorund in decerver becuase shit needed to be fixed and i didnt want to wait till morning.

what's the state of this now?

**Pull request closed without merging**
